<a href="https://colab.research.google.com/github/NEHA1039/DSBDL-LAB/blob/main/assignment_dsbdl_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("/content/iris.csv")

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df.head(5)

   Id  SepalLength  SepalWidth  PetalLength  PetalWidth Species
0   1          5.1         3.5          1.4         0.2  Setosa
1   2          4.9         3.0          1.4         0.2  Setosa
2   3          4.7         3.2          1.3         0.2  Setosa
3   4          4.6         3.1          1.5         0.2  Setosa
4   5          5.0         3.6          1.4         0.2  Setosa

In [7]:
df.tail(5)

      Id  SepalLength  SepalWidth  PetalLength  PetalWidth    Species
145  146          6.7         3.0          5.2         2.3  Virginica
146  147          6.3         2.5          5.0         1.9  Virginica
147  148          6.5         3.0          5.2         2.0  Virginica
148  149          6.2         3.4          5.4         2.3  Virginica
149  150          5.9         3.0          5.1         1.8  Virginica

In [8]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [9]:
df.columns

Index(['Id', 'SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth',
       'Species'],
      dtype='object')

In [10]:
df.shape

(150, 6)

In [11]:
df.dtypes

Id               int64
SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Species         object
dtype: object

In [12]:
df.iloc[5]

Id                  6
SepalLength       5.4
SepalWidth        3.9
PetalLength       1.7
PetalWidth        0.4
Species        Setosa
Name: 5, dtype: object

In [13]:
df.isnull()

        Id  SepalLength  SepalWidth  PetalLength  PetalWidth  Species
0    False        False       False        False       False    False
1    False        False       False        False       False    False
2    False        False       False        False       False    False
3    False        False       False        False       False    False
4    False        False       False        False       False    False
..     ...          ...         ...          ...         ...      ...
145  False        False       False        False       False    False
146  False        False       False        False       False    False
147  False        False       False        False       False    False
148  False        False       False        False       False    False
149  False        False       False        False       False    False

[150 rows x 6 columns]

In [14]:
df.isna()

        Id  SepalLength  SepalWidth  PetalLength  PetalWidth  Species
0    False        False       False        False       False    False
1    False        False       False        False       False    False
2    False        False       False        False       False    False
3    False        False       False        False       False    False
4    False        False       False        False       False    False
..     ...          ...         ...          ...         ...      ...
145  False        False       False        False       False    False
146  False        False       False        False       False    False
147  False        False       False        False       False    False
148  False        False       False        False       False    False
149  False        False       False        False       False    False

[150 rows x 6 columns]

In [15]:
from sklearn import preprocessing

In [17]:

x=df[['PetalWidth']].values.astype(float)
min_max_scaler=preprocessing.MinMaxScaler()
x_scaler=min_max_scaler.fit_transform(x)
df_normalized=pd.DataFrame(x_scaler)

In [18]:
df_normalized

            0
0    0.041667
1    0.041667
2    0.041667
3    0.041667
4    0.041667
..        ...
145  0.916667
146  0.750000
147  0.791667
148  0.916667
149  0.708333

[150 rows x 1 columns]

In [19]:
from sklearn import preprocessing

In [20]:
df['Species'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

In [21]:
label_encoder=preprocessing.LabelEncoder()

In [23]:
df['Species']=label_encoder.fit_transform(df['Species'])
df['Species'].unique()

array([0, 1, 2])