<a href="https://colab.research.google.com/github/NEHA1039/DSBDL-LAB/blob/main/dsbdl_assignment__3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {'AgeGroup': ['10-20','20-30','30-40','40-50','50-60','60-70'],
        'Income': [30000, 50000, 40000, 35000, 60000, 45000]}
df = pd.DataFrame(data)

In [ ]:
df.head(2)

  AgeGroup  Income
0    10-20   30000
1    20-30   50000

In [ ]:
df.tail(2)

  AgeGroup  Income
4    50-60   60000
5    60-70   45000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   AgeGroup  6 non-null      object
 1   Income    6 non-null      int64
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

             Income
count      6.000000
mean   43333.333333
std    10801.234497
min    30000.000000
25%    36250.000000
50%    42500.000000
75%    48750.000000
max    60000.000000

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].agg(['mean', 'median', 'min', 'max', 'std'])
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
              mean   median    min    max  std
AgeGroup
10-20     30000.0  30000.0  30000  30000  NaN
20-30     50000.0  50000.0  50000  50000  NaN
30-40     40000.0  40000.0  40000  40000  NaN
40-50     35000.0  35000.0  35000  35000  NaN
50-60     60000.0  60000.0  60000  60000  NaN
60-70     45000.0  45000.0  45000  45000  NaN

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].describe()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
           count     mean  std      min      25%      50%      75%      max
AgeGroup
10-20       1.0  30000.0  NaN  30000.0  30000.0  30000.0  30000.0  30000.0
20-30       1.0  50000.0  NaN  50000.0  50000.0  50000.0  50000.0  50000.0
30-40       1.0  40000.0  NaN  40000.0  40000.0  40000.0  40000.0  40000.0
40-50       1.0  35000.0  NaN  35000.0  35000.0  35000.0  35000.0  35000.0
50-60       1.0  60000.0  NaN  60000.0  60000.0  60000.0  60000.0  60000.0
60-70       1.0  45000.0  NaN  45000.0  45000.0  45000.0  45000.0  45000.0

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].mean()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000.0
20-30    50000.0
30-40    40000.0
40-50    35000.0
50-60    60000.0
60-70    45000.0
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].median()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000.0
20-30    50000.0
30-40    40000.0
40-50    35000.0
50-60    60000.0
60-70    45000.0
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].std()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20   NaN
20-30   NaN
30-40   NaN
40-50   NaN
50-60   NaN
60-70   NaN
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].var()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20   NaN
20-30   NaN
30-40   NaN
40-50   NaN
50-60   NaN
60-70   NaN
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].min()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000
20-30    50000
30-40    40000
40-50    35000
50-60    60000
60-70    45000
Name: Income, dtype: int64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].max()
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000
20-30    50000
30-40    40000
40-50    35000
50-60    60000
60-70    45000
Name: Income, dtype: int64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].quantile(.25)
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000.0
20-30    50000.0
30-40    40000.0
40-50    35000.0
50-60    60000.0
60-70    45000.0
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].quantile(.5)
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000.0
20-30    50000.0
30-40    40000.0
40-50    35000.0
50-60    60000.0
60-70    45000.0
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].quantile(.75)
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 AgeGroup
10-20    30000.0
20-30    50000.0
30-40    40000.0
40-50    35000.0
50-60    60000.0
60-70    45000.0
Name: Income, dtype: float64

In [ ]:
grouped_stats = df.groupby('AgeGroup')['Income'].describe().to_dict('index')
print("Grouped Summary Statistics:\n", grouped_stats)

Grouped Summary Statistics:
 {'10-20': {'count': 1.0, 'mean': 30000.0, 'std': nan, 'min': 30000.0, '25%': 30000.0, '50%': 30000.0, '75%': 30000.0, 'max': 30000.0}, '20-30': {'count': 1.0, 'mean': 50000.0, 'std': nan, 'min': 50000.0, '25%': 50000.0, '50%': 50000.0, '75%': 50000.0, 'max': 50000.0}, '30-40': {'count': 1.0, 'mean': 40000.0, 'std': nan, 'min': 40000.0, '25%': 40000.0, '50%': 40000.0, '75%': 40000.0, 'max': 40000.0}, '40-50': {'count': 1.0, 'mean': 35000.0, 'std': nan, 'min': 35000.0, '25%': 35000.0, '50%': 35000.0, '75%': 35000.0, 'max': 35000.0}, '50-60': {'count': 1.0, 'mean': 60000.0, 'std': nan, 'min': 60000.0, '25%': 60000.0, '50%': 60000.0, '75%': 60000.0, 'max': 60000.0}, '60-70': {'count': 1.0, 'mean': 45000.0, 'std': nan, 'min': 45000.0, '25%': 45000.0, '50%': 45000.0, '75%': 45000.0, 'max': 45000.0}}